let quotes = [
  {
    title: "Compound Yourself",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "You also want to be an exponential curve yourself—you should aim for your life to follow an ever-increasing up-and-to-the-right trajectory. It’s important to move towards a career that has a compounding effect—most careers progress fairly linearly.\n\nYou don't want to be in a career where people who have been doing it for two years can be as effective as people who have been doing it for twenty—your rate of learning should always be high. As your career progresses, each unit of work you do should generate more and more results. There are many ways to get this leverage, such as capital, technology, brand, network effects, and managing people.\n\nMost people get bogged down in linear opportunities. Be willing to let small opportunities go to focus on potential step changes.",
  },
  {
    title: "Compound Yourself",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "I think the biggest competitive advantage in business—either for a company or for an individual’s career—is long-term thinking with a broad view of how different systems in the world are going to come together. One of the notable aspects of compound growth is that the furthest out years are the most important. In a world where almost no one takes a truly long-term view, the market richly rewards those who do.",
  },
  {
    title: "Compound Yourself",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Compounding is magic. Look for it everywhere. Exponential curves are the key to wealth generation.",
  },
  {
    title: "Have Almost Too-Much Self Belief",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Self-belief is immensely powerful. The most successful people I know believe in themselves almost to the point of delusion.\n\nIf you don’t believe in yourself, it’s hard to let yourself have contrarian ideas about the future. But this is where most value gets created.",
  },
  {
    title: "Have Almost Too-Much Self Belief",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Managing your own morale—and your team’s morale—is one of the greatest challenges of most endeavors. It’s almost impossible without a lot of self-belief. And unfortunately, the more ambitious you are, the more the world will try to tear you down.",
  },
  {
    title: "Have Almost Too-Much Self Belief",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Most highly successful people have been really right about the future at least once at a time when people thought they were wrong. If not, they would have faced much more competition.",
  },
  {
    title: "Have Almost Too-Much Self Belief",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Self-belief must be balanced with self-awareness. I used to hate criticism of any sort and actively avoided it. Now I try to always listen to it with the assumption that it’s true, and then decide if I want to act on it or not. Truth-seeking is hard and often painful, but it is what separates self-belief from self-delusion.",
  },
  {
    title: "Learn To Think Independently",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Thinking from first principles and trying to generate new ideas is fun, and finding people to exchange them with is a great way to get better at this. The next step is to find easy, fast ways to test these ideas in the real world.",
  },
  {
    title: "Learn To Think Independently",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "One of the most powerful lessons to learn is that you can figure out what to do in situations that seem to have no solution. The more times you do this, the more you will believe it. Grit comes from learning you can get back up after you get knocked down.",
  },
  {
    title: "Get Good At 'Sales'",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "All great careers, to some degree, become sales jobs. You have to evangelize your plans to customers, prospective employees, the press, investors, etc. This requires an inspiring vision, strong communication skills, some degree of charisma, and evidence of execution ability.",
  },
  {
    title: "Get Good At 'Sales'",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "The best way to be good at sales is to genuinely believe in what you’re selling. Selling what you truly believe in feels great, and trying to sell snake oil feels awful.\n\nGetting good at sales is like improving at any other skill—anyone can get better at it with deliberate practice. But for some reason, perhaps because it feels distasteful, many people treat it as something unlearnable.",
  },
  {
    title: "Get Good At 'Sales'",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "My other big sales tip is to show up in person whenever it’s important. When I was first starting out, I was always willing to get on a plane. It was frequently unnecessary, but three times it led to career-making turning points for me that otherwise would have gone the other way.",
  },
  {
    title: "Make It Easy To Take Risks",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Most people overestimate risk and underestimate reward. Taking risks is important because it’s impossible to be right all the time—you have to try many things and adapt quickly as you learn more.",
  },
  {
    title: "Make It Easy To Take Risks",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "When people get used to a comfortable life, a predictable job, and a reputation of succeeding at whatever they do, it gets very hard to leave that behind (and people have an incredible ability to always match their lifestyle to next year’s salary). Even if they do leave, the temptation to return is great. It’s easy—and human nature—to prioritize short-term gain and convenience over long-term fulfillment.",
  },
  {
    title: "Make It Easy To Take Risks",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "It’s often easier to take risks early in your career; you don’t have much to lose, and you potentially have a lot to gain. Once you’ve gotten yourself to a point where you have your basic obligations covered you should try to make it easy to take risks. Look for small bets you can make where you lose 1x if you’re wrong but make 100x if it works. Then make a bigger bet in that direction.",
  },
  {
    title: "Focus",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Almost everyone I’ve ever met would be well-served by spending more time thinking about what to focus on. It is much more important to work on the right thing than it is to work many hours. Most people waste most of their time on stuff that doesn’t matter.\n\nOnce you have figured out what to do, be unstoppable about getting your small handful of priorities accomplished quickly. I have yet to meet a slow-moving person who is very successful.",
  },
  {
    title: "Work Hard",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Extreme people get extreme results. Working a lot comes with huge life trade-offs, and it’s perfectly rational to decide not to do it. But it has a lot of advantages. As in most cases, momentum compounds, and success begets success.",
  },
  {
    title: "Work Hard",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "You can get to about the 90th percentile in your field by working either smart or hard, which is still a great accomplishment. But getting to the 99th percentile requires both—you will be competing with other very talented people who will have great ideas and be willing to work a lot.",
  },
  {
    title: "Work Hard",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "One of the great joys in life is finding your purpose, excelling at it, and discovering that your impact matters to something larger than yourself.",
  },
  {
    title: "Work Hard",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "You have to figure out how to work hard without burning out. People find their own strategies for this, but one that almost always works is to find work you like doing with people you enjoy spending a lot of time with.\n\nOne more thought about working hard: do it at the beginning of your career. Hard work compounds like interest, and the earlier you do it, the more time you have for the benefits to pay off. It’s also easier to work hard when you have fewer other responsibilities, which is frequently but not always the case when you’re young.",
  },
  {
    title: "Be Bold",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "I believe that it’s easier to do a hard startup than an easy startup. People want to be part of something exciting and feel that their work matters.\n\nIf you are making progress on an important problem, you will have a constant tailwind of people wanting to help you. Let yourself grow more ambitious, and don’t be afraid to work on what you really want to work on.\n\nFollow your curiosity. Things that seem exciting to you will often seem exciting to other people too.",
  },
  {
    title: "Be Willful",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "A big secret is that you can bend the world to your will a surprising percentage of the time—most people don’t even try, and just accept that things are the way that they are.\n\nPeople have an enormous capacity to make things happen. A combination of self-doubt, giving up too early, and not pushing hard enough prevents most people from ever reaching anywhere near their potential.\n\nAsk for what you want. You usually won’t get it, and often the rejection will be painful. But when this works, it works surprisingly well.",
  },
  {
    title: "Be Willful",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Almost always, the people who say “I am going to keep going until this works, and no matter what the challenges are I’m going to figure them out”, and mean it, go on to succeed. They are persistent long enough to give themselves a chance for luck to go their way.",
  },
  {
    title: "Be Willful",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "To be willful, you have to be optimistic—hopefully this is a personality trait that can be improved with practice. I have never met a very successful pessimistic person.",
  },
  {
    title: "Be Hard To Compete With",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Most people understand that companies are more valuable if they are difficult to compete with. This is important, and obviously true. But this holds true for you as an individual as well. If what you do can be done by someone else, it eventually will be, and for less money.\n\nThe best way to become difficult to compete with is to build up leverage. For example, you can do it with personal relationships, by building a strong personal brand, or by getting good at the intersection of multiple different fields. There are many other strategies, but you have to figure out some way to do it.",
  },
  {
    title: "Build A Network",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Great work requires teams. Developing a network of talented people to work with—sometimes closely, sometimes loosely—is an essential part of a great career. The size of the network of really talented people you know often becomes the limiter for what you can accomplish.\n\nAn effective way to build a network is to help people as much as you can. Doing this, over a long period of time, is what lead to most of my best career opportunities and three of my four best investments. I’m continually surprised how often something good happens to me because of something I did to help a founder ten years ago.",
  },
  {
    title: "Build A Network",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "One of the best ways to build a network is to develop a reputation for really taking care of the people who work with you. Be overly generous with sharing the upside; it will come back to you 10x. Also, learn how to evaluate what people are great at, and put them in those roles. (This is the most important thing I have learned about management, and I haven’t read much about it.) You want to have a reputation for pushing people hard enough that they accomplish more than they thought they could, but not so hard they burn out.\n\nA special case of developing a network is finding someone eminent to take a bet on you, ideally early in your career. The best way to do this, no surprise, is to go out of your way to be helpful. (And remember that you have to pay this forward at some point later!)",
  },
  {
    title: "Build A Network",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Everyone is better at some things than others. Define yourself by your strengths, not your weaknesses. Acknowledge your weaknesses and figure out how to work around them, but don’t let them stop you from doing what you want to do. “I can’t do X because I’m not good at Y” is something I hear from entrepreneurs surprisingly often, and almost always reflects a lack of creativity. The best way to make up for your weaknesses is to hire complementary team members instead of just hiring people who are good at the same things you are.",
  },
  {
    title: "You Get Rich By Owning Things",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "You get truly rich by owning things that increase rapidly in value.\n\nThis can be a piece of a business, real estate, natural resource, intellectual property, or other similar things. But somehow or other, you need to own equity in something, instead of just selling your time. Time only scales linearly.\n\nThe best way to make things that increase rapidly in value is by making things people want at scale.",
  },
  {
    title: "Be Internally Driven",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "Most people are primarily externally driven; they do what they do because they want to impress other people. This is bad for many reasons, but here are two important ones.\n\nFirst, you will work on consensus ideas and on consensus career tracks.  You will care a lot—much more than you realize—if other people think you’re doing the right thing. This will probably prevent you from doing truly interesting work, and even if you do, someone else would have done it anyway.\n\nSecond, you will usually get risk calculations wrong. You’ll be very focused on keeping up with other people and not falling behind in competitive games, even in the short term.\n\nSmart people seem to be especially at risk of such externally-driven behavior. Being aware of it helps, but only a little—you will likely have to work super-hard to not fall in the mimetic trap.",
  },
  {
    title: "Be Internally Driven",
    source_name: "Sam Altman - How To Be Successful",
    source_link: "https://blog.samaltman.com/how-to-be-successful",
    content: "The most successful people I know are primarily internally driven; they do what they do to impress themselves and because they feel compelled to make something happen in the world. After you’ve made enough money to buy whatever you want and gotten enough social status that it stops being fun to get more, this is the only force I know of that will continue to drive you to higher levels of performance.\n\nThis is why the question of a person’s motivation is so important. It’s the first thing I try to understand about someone. The right motivations are hard to define a set of rules for, but you know it when you see it.",
  },
  {
    title: "Make Something People Want",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "Nothing else you do will matter if you are not making something people want. You can be the best spokesperson, the best fundraiser, the best programmer, but if you aren’t building a product that satisfies a real need, you’ll never succeed.\n\nMy advice to those of you who are still looking for an idea is to solve a problem that you yourself have. Then you’ll know it’s something at least one person really wants. And when you’re part of the target market, you’ll have insights about it that you wouldn’t otherwise.\n\nBut you should graduate from making something just for yourself to making something for other people as fast as you can. And to know what they want, you have to understand them. Do they like what you’ve made so far? If not, why not? Talk to your users as much as you can, even if that means doing things that don’t scale early on. I don’t know of a single case of a startup that felt they spent too much time talking to users.",
  },
  {
    title: "Stay Focused",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "One of the most conspicuous patterns we’ve seen among the thousand startups we’ve funded is that the most successful founders are always totally focused on their product and their users. To the point of being fanatical. The best founders don’t have time to get caught up in other things.\n\nHere’s a list of things that I see easily distract founders.\n\n“Grabbing coffee” with investors\nTalking with potential acquirers\nNetworking\nRecruiting boards of advisors\nDoing a 'partnership,' thinking it will get you more users\nSpending time on PR before you have made something people want\nArguing on social media\nGoing to conferences",
  },
  {
    title: "Measure Your Growth",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "If you have a good growth rate, which in a startup means at least 10% per month, you’re on the right track. And if you don’t, you’re missing at least one of the two ingredients I mentioned. You’re either making the wrong thing, or not focusing enough.",
  },
  {
    title: "Measure Your Growth",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "You make what you measure. Pick a number you want to grow, and focus on that. The best metric to choose is good old fashioned revenue. There’s no better test of whether you’re really making something people want.",
  },
  {
    title: "Measure Your Growth",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "Founders who are making the wrong thing are often in denial about it. Founders who are wasting their time on inessential stuff are often in denial about it. Denial is the silent killer of startups. But if you hold yourself to growth targets, you can’t remain in denial. The numbers, good or bad, are staring you in the face.",
  },
  {
    title: "Know If You're Default Alive",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "Default alive means if your expenses stay the same and your revenue continues to grow at the rate it’s been growing, you get to breakeven before you run out of money. Default dead means you don’t.\n\nWe now ask all YC founders to begin their investor updates to us by saying which of the two they are. As well as telling us how the startup is doing, it’s a good way to yank the founders out of denial.",
  },
  {
    title: "Keep Expenses Low",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "Why do startups run out of money? By spending too much. And since the main expense in most startups is salaries, spending too much = hiring too many people. Overhiring is the big mistake in the second phase of a startup, as making something no one wants is in the first phase.\n\nSo after you raise money, be very conservative about how you spend it. Hire for the pessimistic case. Assume it will take longer than you expect to get things working. If there’s one thing you can forsee in a startup, it’s unforseen problems.",
  },
  {
    title: "Fundraising Gets Harder",
    source_name: "Jessica Livingston - How Not To Fail (At A Startup)",
    source_link: "https://blog.ycombinator.com/how-not-to-fail/",
    content: "The reason startups get so slammed when they have to raise money as an ugly duckling is that later rounds of fundraising get much harder. Founders who had a fairly easy time raising a seed round think it will be just as easy to raise a series A. It’s not.\n\nSeries A investors have a totally different attitude from seed investors. Seed investors are looking for promise. Series A investors are looking for performance. They know that all the returns from venture investing are concentrated in the big winners. So they want to invest in you only if you are clearly on a path to being a big winner.",
  },
  {
    title: "How To Do Well As An Investor",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "To do well as an investor, you need to do three things: get access to good investment opportunities, make good decisions about what to invest in, and get the companies you want to invest in to choose you as an investor. ",
  },
  {
    title: "Access To Investments",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "Getting access to investment opportunities is the easiest of the three categories: you can just work hard.  It’s surprising that most investors don’t work hard, but it’s true, and a bug that you can exploit.\n\nPutting a lot of energy into networking actually works, as long as you aren’t just trying to touch base when people can find some time away from their crazy calendars to grab coffee.  If you actually figure out how to help other investors you respect, and to really help good founders, then good investment opportunities will come your way.",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "Great founders are the key to great startups.  One way to do really well as a startup investor is to get good at predicting who is going to be great before they are.\n\nSo how do you identify future greatness? It’s easiest if you get to meet people in person, several times.  If you meet someone three times in three months, and notice detectable improvement each time, pay attention to that.  The rate of improvement is often more important than the current absolute ability (in particular, younger founders can sometimes improve extremely quickly).\n\nThe main question I ask myself when I meet a founder is if I’d work for that person.  The second question I ask myself is if I can imagine them taking over their industry.",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "I look for founders who are scrappy and formidable at the same time (a rarer combination than it sounds); mission-oriented, obsessed with their companies, relentless, and determined; extremely smart (necessary but certainly not sufficient); decisive, fast-moving, and willful; courageous, high-conviction, and willing to be misunderstood; strong communicators and infectious evangelists; and capable of becoming tough and ambitious. ",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "In addition to learning to predict who will become great founders, you have to be at least okay at predicting what markets will be good.\n\nStartups are likely to happen in many more industries—startups can win wherever costs can be low and cycle time can be fast.  Startups do particularly well in industries with rapid technological change, because their fundamental advantages over large competitors are speed and focus.  A higher rate of change gives startups more opportunities to be right and the large competitor more opportunities to stumble.",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The best companies tend to have the courage to lead the market by a couple of years, but they know the secret for telling the difference between a real trend and a fake trend.  For a real trend, even if there aren’t many users, they use the new platform a lot and love it. For example, although the iPhone was derided for not having many users in its first year or two, most people who had an iPhone raved about it in a way that they never did about previous smartphones.\n\nThe very best companies tend to ride the wave of a new, important, and rapidly growing platform.",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The spectral signatures of the best companies I’ve invested in are remarkably similar.  They usually have most of the following characteristics: compelling founders, a mission that attracts talented people into the startup’s orbit, a product so good that people spontaneously tell their friends about it, a rapidly growing market, a network effect and low marginal costs, the ability to grow fast, and a product that is either fundamentally new or 10x better than existing options.",
  },
  {
    title: "Decisions About Who To Invest In",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The central learning of my career so far has been that you can and should scale up things that are working.  The power of scale, and the emergent behavior that sometimes comes from it, is tremendous. I think about the potential energy of future scale for every investment I make.  Most people seem terrible at this, so it’s another bug you can exploit.",
  },
  {
    title: "Close Rate Of Investments",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The better the investment opportunity is (i.e., expected value relative to valuation), the harder it usually is to get the company to choose you as an investor.\n\nTraditional sales tactics works pretty well here.  Spend a lot of time with the founder, explain what you’re willing to do to help them, ask founders you’ve worked with in the past to call them, etc.\n\nA reputation for being above-and-beyond helpful and accessible is worth a lot here, and rare among all but the best investors.  A reputation for being founder-friendly helps too. What helps most of all is other founders you’ve previously invested in saying “that person was my best investor by far”.\n\nIn addition to helping get access to investment opportunities, a strong brand also helps close them.  It’s a nice tailwind if you can get yourself to the place where simply taking your money helps a company get taken more seriously.",
  },
  {
    title: "Close Rate Of Investments",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The best way to have a poor close rate is to not treat founders like peers.  If you’re picking well, you should be investing in founders that you think of as your peers at least.  Founders have a sixth sense for who is going to treat them like a peer and who is going to treat them like a boss.  And if they’re good, they know you’re failing an intelligence test if you act like their boss.",
  },
  {
    title: "Help Founders",
    source_name: "Sam Altman - How To Invest In Startups",
    source_link: "https://blog.samaltman.com/how-to-invest-in-startups",
    content: "The most important way to help founders is to get them to be more ambitious—to think bigger and to have more self-belief.  Help them set ambitious but achievable goals. Momentum is important and self-reinforcing—most people set goals that they expect to be just out of reach, which is usually demotivating.  It’s better to continuously set goals that you can just barely hit.\n\nThe second most important thing to do is to give them specific, tactical advice (instead of general strategy) about how to achieve their goals.  Good tactical advice is something like “it seems like you’ve figured out yourself how to do sales for this company, so here is where to look and what to look for in your first sales hire, and here is the sales tool you should use”.",
  },
  {
    title: "Ways To Get Rich",
    source_name: "Paul Graham - Inequality",
    source_link: "http://www.paulgraham.com/ineq.html",
    content: "But while there are a lot of people who get rich through rent-seeking of various forms, and a lot who get rich by playing zero-sum games, there are also a significant number who get rich by creating wealth. And creating wealth, as a source of economic inequality, is different from taking it — not just morally, but also practically, in the sense that it is harder to eradicate. One reason is that variation in productivity is accelerating. The rate at which individuals can create wealth depends on the technology available to them, and that grows exponentially. The other reason creating wealth is such a tenacious source of inequality is that it can expand to accommodate a lot of people.",
  },
  {
    title: "Paradox Of Wealth Inequality",
    source_name: "Paul Graham - Inequality",
    source_link: "http://www.paulgraham.com/ineq.html",
    content: "Most people who get rich tend to be fairly driven. Whatever their other flaws, laziness is usually not one of them. Suppose new policies make it hard to make a fortune in finance. Does it seem plausible that the people who currently go into finance to make their fortunes will continue to do so, but be content to work for ordinary salaries? The reason they go into finance is not because they love finance but because they want to get rich. If the only way left to get rich is to start startups, they'll start startups. They'll do well at it too, because determination is the main factor in the success of a startup. And while it would probably be a good thing for the world if people who wanted to get rich switched from playing zero-sum games to creating wealth, that would not only not eliminate great variations in wealth, but might even exacerbate them. In a zero-sum game there is at least a limit to the upside. Plus a lot of the new startups would create new technology that further accelerated variation in productivity.",
  },
  {
    title: "Paradox Of Wealth Inequality",
    source_name: "Paul Graham - Inequality",
    source_link: "http://www.paulgraham.com/ineq.html",
    content: "You can't prevent great variations in wealth without preventing people from getting rich, and you can't do that without preventing them from starting startups.\n\nSo let's be clear about that. Eliminating great variations in wealth would mean eliminating startups. And that doesn't seem a wise move. Especially since it would only mean you eliminated startups in your own country. Ambitious people already move halfway around the world to further their careers, and startups can operate from anywhere nowadays. So if you made it impossible to get rich by creating wealth in your country, people who wanted to do that would just leave and do it somewhere else. Which would certainly get you a lower Gini coefficient, along with a lesson in being careful what you ask for.",
  },
  // {
  //   title: "",
  //   source_name: "",
  //   source_link: "",
  //   content: "",
  // },
];

export default quotes;
